services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"